// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lbrty/observer/internal/domain/project (interfaces: PermissionLoader)
//
// Generated by this command:
//
//	mockgen -destination=mock/repository.go -package=mock github.com/lbrty/observer/internal/domain/project PermissionLoader
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	project "github.com/lbrty/observer/internal/domain/project"
	ulid "github.com/oklog/ulid/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionLoader is a mock of PermissionLoader interface.
type MockPermissionLoader struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionLoaderMockRecorder
	isgomock struct{}
}

// MockPermissionLoaderMockRecorder is the mock recorder for MockPermissionLoader.
type MockPermissionLoaderMockRecorder struct {
	mock *MockPermissionLoader
}

// NewMockPermissionLoader creates a new mock instance.
func NewMockPermissionLoader(ctrl *gomock.Controller) *MockPermissionLoader {
	mock := &MockPermissionLoader{ctrl: ctrl}
	mock.recorder = &MockPermissionLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionLoader) EXPECT() *MockPermissionLoaderMockRecorder {
	return m.recorder
}

// GetPermission mocks base method.
func (m *MockPermissionLoader) GetPermission(ctx context.Context, userID ulid.ULID, projectID string) (*project.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermission", ctx, userID, projectID)
	ret0, _ := ret[0].(*project.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermission indicates an expected call of GetPermission.
func (mr *MockPermissionLoaderMockRecorder) GetPermission(ctx, userID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermission", reflect.TypeOf((*MockPermissionLoader)(nil).GetPermission), ctx, userID, projectID)
}

// IsProjectOwner mocks base method.
func (m *MockPermissionLoader) IsProjectOwner(ctx context.Context, userID ulid.ULID, projectID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProjectOwner", ctx, userID, projectID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProjectOwner indicates an expected call of IsProjectOwner.
func (mr *MockPermissionLoaderMockRecorder) IsProjectOwner(ctx, userID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProjectOwner", reflect.TypeOf((*MockPermissionLoader)(nil).IsProjectOwner), ctx, userID, projectID)
}
