repos:
- repo: https://github.com/PyCQA/isort
  rev: '5.10.1'
  hooks:
  - id: isort
    args: [-c]
- repo: https://github.com/psf/black
  rev: '22.6.0'
  hooks:
    - id: black
      language_version: python3
- repo: https://github.com/PyCQA/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    additional_dependencies:
      - flake8-docstrings==1.6.0
    exclude: "^docs/"
- repo: https://github.com/seddonym/import-linter
  rev: '1.2.7'
  hooks:
    - id: import-linter
