version: "3.8"
services:
  observer:
    image: sultaniman/observer:latest-slim
    environment:
      DB_URI: postgresql+asyncpg://postgres:postgres@db:5433/observer
      KEYSTORE_PATH: /keys
      STORAGE_ROOT: /documents
    ports:
      - "127.0.0.1:4040:8000"
    volumes:
      - ./keys:/keys
      - ./documents:/documents
    depends_on:
      - db
      - migrations
  migrations:
    image: sultaniman/observer:latest-slim
    environment:
      DB_URI: postgresql+asyncpg://postgres:postgres@db:5433/observer
    command: sleep 5 && python -m observer db upgrade
    depends_on:
      - db
  db:
    image: postgres:14.5
    volumes:
      - postgres_observer_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: observer
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  postgres_observer_data: {}
