[tool.poetry]
name = "observer"
version = "0.1.0"
description = "Collection of useful types to use with mypy or for typehints"
authors = ["Sultan Iman <sultan.imanhodjaev[at]gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.79.0"
pytoolz = "^0.1.7"
alembic = "^1.8.1"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.39"}
pydantic = {extras = ["dotenv"], version = "^1.9.1"}
typer = "^0.6.1"
asyncpg = "^0.26.0"
greenlet = "^1.1.2"
shortuuid = "^1.0.9"
types-SQLAlchemy = "^1.4.50"
cryptography = "^37.0.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
black = "^22.6.0"
flake8 = "^4.0.1"
isort = "^5.10.1"
mypy = "^0.961"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py310"]
include = "\\.pyi?$"
extend-exclude = """
/(
  # The following are specific to Black, you probably don't want those.
  | \\.venv
  | \\.git
  | \\.idea
)/
"""
preview = true

[tool.mypy]
exclude = [".venv", ".git", ".idea"]
ignore_missing_imports = true
