[tool.poetry]
name = "observer"
version = "0.1.0"
description = "Collection of useful types to use with mypy or for typehints"
authors = ["Sultan Iman <sultan.imanhodjaev[at]gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.85.1"
pytoolz = "^0.1.7"
alembic = "^1.8.1"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.42"}
pydantic = {extras = ["dotenv"], version = "^1.10.2"}
typer = "^0.6.1"
asyncpg = "^0.26.0"
greenlet = "^1.1.3"
shortuuid = "^1.0.9"
types-SQLAlchemy = "^1.4.53"
cryptography = "^38.0.1"
uvicorn = {extras = ["standard"], version = "^0.19.0"}
structlog = "^22.1.0"
passlib = "^1.7.4"
bcrypt = "^4.0.1"
totp = "^1.3.0"
pyjwt = "^2.6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
black = "^22.10.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
mypy = "^0.982"
pre-commit = "^2.20.0"
rich = "^12.6.0"
autoflake = "^1.7.6"
pytest-cov = "^4.0.0"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^0.21.0"
ruff = "^0.0.118"
pytest-asyncio = "^0.20.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# Tool configurations
[tool.black]
line-length = 120
target-version = ["py310"]
include = "\\.pyi?$"
extend-exclude = """
/(
  # The following are specific to Black, you probably don't want those.
  | \\.venv
  | \\.git
  | \\.idea
)/
"""
preview = true

[tool.mypy]
exclude = [".venv", ".git", ".idea"]
ignore_missing_imports = true

[tool.isort]
profile = "black"
src_paths = ["migrations", "observer", "tests"]

[tool.ruff]
line-length = 120
ignore = ["E999"]

[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true
recursive = true
in-place = true
exclude = ".venv,.git,.idea"

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--cov=observer --cov-report=term-missing --cov-report=xml:reports/coverage.xml --junit-xml=reports/tests.xml"

[tool.coverage.run]
branch = true
relative_files = false
source = ["observer"]

[tool.coverage.report]
show_missing = true
