[[main]]
  name = "Guide"
  pageRef = "/docs/guide"
  weight = 1

[[main]]
  name = "Developers"
  pageRef = "/docs/developers"
  weight = 2

[[main]]
  name = "ADRs"
  pageRef = "/docs/adr"
  weight = 3

[[main]]
  name = "Plans"
  pageRef = "/docs/plans"
  weight = 4

[[main]]
  name = "GitHub"
  url = "https://github.com/lbrty/observer"
  weight = 10
  [main.params]
    icon = "github"
