export type { Icon } from "@phosphor-icons/react";

export {
  ArrowLeftIcon,
  ArrowSquareOutIcon,
  BuildingsIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpDownIcon,
  ChartBarIcon,
  CheckIcon,
  FilesIcon,
  FolderSimpleIcon,
  GearSixIcon,
  GlobeIcon,
  HandHeartIcon,
  HouseSimpleIcon,
  MagnifyingGlassIcon,
  NoteIcon,
  PathIcon,
  PawPrintIcon,
  PencilSimpleIcon,
  PlusIcon,
  SignOutIcon,
  TagIcon,
  TrashIcon,
  UserCircleIcon,
  UsersIcon,
  WarningIcon,
  XIcon,
} from "@phosphor-icons/react";
