export type { Icon } from "@phosphor-icons/react";

export {
  ArrowLeftIcon,
  ArrowSquareOutIcon,
  CalendarBlankIcon,
  BuildingsIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpDownIcon,
  CaretUpIcon,
  ChartBarIcon,
  CheckIcon,
  CopySimpleIcon,
  DownloadSimpleIcon,
  FilesIcon,
  FolderSimpleIcon,
  FunnelIcon,
  GearSixIcon,
  GlobeIcon,
  HandHeartIcon,
  HouseSimpleIcon,
  MagnifyingGlassIcon,
  NoteIcon,
  PathIcon,
  PawPrintIcon,
  PencilSimpleIcon,
  PlusIcon,
  PrinterIcon,
  SignOutIcon,
  TagIcon,
  TrashIcon,
  UserCircleIcon,
  UsersIcon,
  WarningIcon,
  UserFocusIcon,
  XIcon,
} from "@phosphor-icons/react";
