// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lbrty/observer/internal/repository (interfaces: LoginAttemptStore)
//
// Generated by this command:
//
//	mockgen -destination=internal/repository/mock/login_attempt_store.go -package=mock github.com/lbrty/observer/internal/repository LoginAttemptStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginAttemptStore is a mock of LoginAttemptStore interface.
type MockLoginAttemptStore struct {
	ctrl     *gomock.Controller
	recorder *MockLoginAttemptStoreMockRecorder
	isgomock struct{}
}

// MockLoginAttemptStoreMockRecorder is the mock recorder for MockLoginAttemptStore.
type MockLoginAttemptStoreMockRecorder struct {
	mock *MockLoginAttemptStore
}

// NewMockLoginAttemptStore creates a new mock instance.
func NewMockLoginAttemptStore(ctrl *gomock.Controller) *MockLoginAttemptStore {
	mock := &MockLoginAttemptStore{ctrl: ctrl}
	mock.recorder = &MockLoginAttemptStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginAttemptStore) EXPECT() *MockLoginAttemptStoreMockRecorder {
	return m.recorder
}

// ClearAttempts mocks base method.
func (m *MockLoginAttemptStore) ClearAttempts(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAttempts", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearAttempts indicates an expected call of ClearAttempts.
func (mr *MockLoginAttemptStoreMockRecorder) ClearAttempts(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAttempts", reflect.TypeOf((*MockLoginAttemptStore)(nil).ClearAttempts), ctx, email)
}

// IsLocked mocks base method.
func (m *MockLoginAttemptStore) IsLocked(ctx context.Context, email string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLocked", ctx, email)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLocked indicates an expected call of IsLocked.
func (mr *MockLoginAttemptStoreMockRecorder) IsLocked(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLocked", reflect.TypeOf((*MockLoginAttemptStore)(nil).IsLocked), ctx, email)
}

// RecordFailure mocks base method.
func (m *MockLoginAttemptStore) RecordFailure(ctx context.Context, email string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFailure", ctx, email)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordFailure indicates an expected call of RecordFailure.
func (mr *MockLoginAttemptStoreMockRecorder) RecordFailure(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailure", reflect.TypeOf((*MockLoginAttemptStore)(nil).RecordFailure), ctx, email)
}
