// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lbrty/observer/internal/repository (interfaces: UserRepository,CredentialsRepository,MFARepository,VerificationTokenRepository,SessionRepository,PermissionLoader,PermissionRepository,ProjectRepository,CountryRepository,StateRepository,PlaceRepository,OfficeRepository,CategoryRepository,TagRepository,PersonRepository,PersonCategoryRepository,PersonTagRepository,SupportRecordRepository,MigrationRecordRepository,HouseholdRepository,HouseholdMemberRepository,PersonNoteRepository,DocumentRepository,PetRepository,ReportRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/repository.go -package=mock github.com/lbrty/observer/internal/repository UserRepository,CredentialsRepository,MFARepository,VerificationTokenRepository,SessionRepository,PermissionLoader,PermissionRepository,ProjectRepository,CountryRepository,StateRepository,PlaceRepository,OfficeRepository,CategoryRepository,TagRepository,PersonRepository,PersonCategoryRepository,PersonTagRepository,SupportRecordRepository,MigrationRecordRepository,HouseholdRepository,HouseholdMemberRepository,PersonNoteRepository,DocumentRepository,PetRepository,ReportRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	auth "github.com/lbrty/observer/internal/domain/auth"
	document "github.com/lbrty/observer/internal/domain/document"
	household "github.com/lbrty/observer/internal/domain/household"
	migration "github.com/lbrty/observer/internal/domain/migration"
	note "github.com/lbrty/observer/internal/domain/note"
	person "github.com/lbrty/observer/internal/domain/person"
	pet "github.com/lbrty/observer/internal/domain/pet"
	project "github.com/lbrty/observer/internal/domain/project"
	reference "github.com/lbrty/observer/internal/domain/reference"
	report "github.com/lbrty/observer/internal/domain/report"
	support "github.com/lbrty/observer/internal/domain/support"
	tag "github.com/lbrty/observer/internal/domain/tag"
	user "github.com/lbrty/observer/internal/domain/user"
	ulid "github.com/oklog/ulid/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, u *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, u)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id ulid.ULID) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// GetByIDs mocks base method.
func (m *MockUserRepository) GetByIDs(ctx context.Context, ids []ulid.ULID) ([]*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockUserRepositoryMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockUserRepository)(nil).GetByIDs), ctx, ids)
}

// GetByPhone mocks base method.
func (m *MockUserRepository) GetByPhone(ctx context.Context, phone string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhone", ctx, phone)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhone indicates an expected call of GetByPhone.
func (mr *MockUserRepositoryMockRecorder) GetByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhone", reflect.TypeOf((*MockUserRepository)(nil).GetByPhone), ctx, phone)
}

// List mocks base method.
func (m *MockUserRepository) List(ctx context.Context, filter user.UserListFilter) ([]*user.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*user.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockUserRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, u *user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, u)
}

// UpdateVerified mocks base method.
func (m *MockUserRepository) UpdateVerified(ctx context.Context, id ulid.ULID, verified bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerified", ctx, id, verified)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVerified indicates an expected call of UpdateVerified.
func (mr *MockUserRepositoryMockRecorder) UpdateVerified(ctx, id, verified any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerified", reflect.TypeOf((*MockUserRepository)(nil).UpdateVerified), ctx, id, verified)
}

// MockCredentialsRepository is a mock of CredentialsRepository interface.
type MockCredentialsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialsRepositoryMockRecorder
	isgomock struct{}
}

// MockCredentialsRepositoryMockRecorder is the mock recorder for MockCredentialsRepository.
type MockCredentialsRepositoryMockRecorder struct {
	mock *MockCredentialsRepository
}

// NewMockCredentialsRepository creates a new mock instance.
func NewMockCredentialsRepository(ctrl *gomock.Controller) *MockCredentialsRepository {
	mock := &MockCredentialsRepository{ctrl: ctrl}
	mock.recorder = &MockCredentialsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialsRepository) EXPECT() *MockCredentialsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCredentialsRepository) Create(ctx context.Context, cred *user.Credentials) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCredentialsRepositoryMockRecorder) Create(ctx, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCredentialsRepository)(nil).Create), ctx, cred)
}

// GetByUserID mocks base method.
func (m *MockCredentialsRepository) GetByUserID(ctx context.Context, userID ulid.ULID) (*user.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*user.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockCredentialsRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockCredentialsRepository)(nil).GetByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockCredentialsRepository) Update(ctx context.Context, cred *user.Credentials) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCredentialsRepositoryMockRecorder) Update(ctx, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCredentialsRepository)(nil).Update), ctx, cred)
}

// MockMFARepository is a mock of MFARepository interface.
type MockMFARepository struct {
	ctrl     *gomock.Controller
	recorder *MockMFARepositoryMockRecorder
	isgomock struct{}
}

// MockMFARepositoryMockRecorder is the mock recorder for MockMFARepository.
type MockMFARepositoryMockRecorder struct {
	mock *MockMFARepository
}

// NewMockMFARepository creates a new mock instance.
func NewMockMFARepository(ctrl *gomock.Controller) *MockMFARepository {
	mock := &MockMFARepository{ctrl: ctrl}
	mock.recorder = &MockMFARepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMFARepository) EXPECT() *MockMFARepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMFARepository) Create(ctx context.Context, cfg *user.MFAConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMFARepositoryMockRecorder) Create(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMFARepository)(nil).Create), ctx, cfg)
}

// GetByUserID mocks base method.
func (m *MockMFARepository) GetByUserID(ctx context.Context, userID ulid.ULID) (*user.MFAConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*user.MFAConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockMFARepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockMFARepository)(nil).GetByUserID), ctx, userID)
}

// MockVerificationTokenRepository is a mock of VerificationTokenRepository interface.
type MockVerificationTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockVerificationTokenRepositoryMockRecorder is the mock recorder for MockVerificationTokenRepository.
type MockVerificationTokenRepositoryMockRecorder struct {
	mock *MockVerificationTokenRepository
}

// NewMockVerificationTokenRepository creates a new mock instance.
func NewMockVerificationTokenRepository(ctrl *gomock.Controller) *MockVerificationTokenRepository {
	mock := &MockVerificationTokenRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationTokenRepository) EXPECT() *MockVerificationTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVerificationTokenRepository) Create(ctx context.Context, token *user.VerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVerificationTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Create), ctx, token)
}

// GetByToken mocks base method.
func (m *MockVerificationTokenRepository) GetByToken(ctx context.Context, token string) (*user.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*user.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockVerificationTokenRepositoryMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockVerificationTokenRepository)(nil).GetByToken), ctx, token)
}

// MarkUsed mocks base method.
func (m *MockVerificationTokenRepository) MarkUsed(ctx context.Context, id ulid.ULID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockVerificationTokenRepositoryMockRecorder) MarkUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockVerificationTokenRepository)(nil).MarkUsed), ctx, id)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, session *auth.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, session)
}

// Delete mocks base method.
func (m *MockSessionRepository) Delete(ctx context.Context, id ulid.ULID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepository)(nil).Delete), ctx, id)
}

// DeleteByRefreshToken mocks base method.
func (m *MockSessionRepository) DeleteByRefreshToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRefreshToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByRefreshToken indicates an expected call of DeleteByRefreshToken.
func (mr *MockSessionRepositoryMockRecorder) DeleteByRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRefreshToken", reflect.TypeOf((*MockSessionRepository)(nil).DeleteByRefreshToken), ctx, token)
}

// GetByRefreshToken mocks base method.
func (m *MockSessionRepository) GetByRefreshToken(ctx context.Context, token string) (*auth.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRefreshToken", ctx, token)
	ret0, _ := ret[0].(*auth.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRefreshToken indicates an expected call of GetByRefreshToken.
func (mr *MockSessionRepositoryMockRecorder) GetByRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRefreshToken", reflect.TypeOf((*MockSessionRepository)(nil).GetByRefreshToken), ctx, token)
}

// MockPermissionLoader is a mock of PermissionLoader interface.
type MockPermissionLoader struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionLoaderMockRecorder
	isgomock struct{}
}

// MockPermissionLoaderMockRecorder is the mock recorder for MockPermissionLoader.
type MockPermissionLoaderMockRecorder struct {
	mock *MockPermissionLoader
}

// NewMockPermissionLoader creates a new mock instance.
func NewMockPermissionLoader(ctrl *gomock.Controller) *MockPermissionLoader {
	mock := &MockPermissionLoader{ctrl: ctrl}
	mock.recorder = &MockPermissionLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionLoader) EXPECT() *MockPermissionLoaderMockRecorder {
	return m.recorder
}

// GetPermission mocks base method.
func (m *MockPermissionLoader) GetPermission(ctx context.Context, userID ulid.ULID, projectID string) (*project.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermission", ctx, userID, projectID)
	ret0, _ := ret[0].(*project.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermission indicates an expected call of GetPermission.
func (mr *MockPermissionLoaderMockRecorder) GetPermission(ctx, userID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermission", reflect.TypeOf((*MockPermissionLoader)(nil).GetPermission), ctx, userID, projectID)
}

// IsProjectOwner mocks base method.
func (m *MockPermissionLoader) IsProjectOwner(ctx context.Context, userID ulid.ULID, projectID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProjectOwner", ctx, userID, projectID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsProjectOwner indicates an expected call of IsProjectOwner.
func (mr *MockPermissionLoaderMockRecorder) IsProjectOwner(ctx, userID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProjectOwner", reflect.TypeOf((*MockPermissionLoader)(nil).IsProjectOwner), ctx, userID, projectID)
}

// MockPermissionRepository is a mock of PermissionRepository interface.
type MockPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepositoryMockRecorder
	isgomock struct{}
}

// MockPermissionRepositoryMockRecorder is the mock recorder for MockPermissionRepository.
type MockPermissionRepositoryMockRecorder struct {
	mock *MockPermissionRepository
}

// NewMockPermissionRepository creates a new mock instance.
func NewMockPermissionRepository(ctrl *gomock.Controller) *MockPermissionRepository {
	mock := &MockPermissionRepository{ctrl: ctrl}
	mock.recorder = &MockPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepository) EXPECT() *MockPermissionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPermissionRepository) Create(ctx context.Context, p *project.ProjectPermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPermissionRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionRepository)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockPermissionRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPermissionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPermissionRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockPermissionRepository) GetByID(ctx context.Context, id string) (*project.ProjectPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*project.ProjectPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPermissionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPermissionRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPermissionRepository) List(ctx context.Context, projectID string) ([]*project.ProjectPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, projectID)
	ret0, _ := ret[0].([]*project.ProjectPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPermissionRepositoryMockRecorder) List(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPermissionRepository)(nil).List), ctx, projectID)
}

// ListByUserID mocks base method.
func (m *MockPermissionRepository) ListByUserID(ctx context.Context, userID string) ([]*project.ProjectPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*project.ProjectPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockPermissionRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockPermissionRepository)(nil).ListByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockPermissionRepository) Update(ctx context.Context, p *project.ProjectPermission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPermissionRepositoryMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPermissionRepository)(nil).Update), ctx, p)
}

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectRepository) Create(ctx context.Context, p *project.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectRepository)(nil).Create), ctx, p)
}

// GetByID mocks base method.
func (m *MockProjectRepository) GetByID(ctx context.Context, id string) (*project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProjectRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProjectRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockProjectRepository) List(ctx context.Context, filter project.ProjectListFilter) ([]*project.Project, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*project.Project)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockProjectRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockProjectRepository) Update(ctx context.Context, p *project.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectRepositoryMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectRepository)(nil).Update), ctx, p)
}

// MockCountryRepository is a mock of CountryRepository interface.
type MockCountryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCountryRepositoryMockRecorder
	isgomock struct{}
}

// MockCountryRepositoryMockRecorder is the mock recorder for MockCountryRepository.
type MockCountryRepositoryMockRecorder struct {
	mock *MockCountryRepository
}

// NewMockCountryRepository creates a new mock instance.
func NewMockCountryRepository(ctrl *gomock.Controller) *MockCountryRepository {
	mock := &MockCountryRepository{ctrl: ctrl}
	mock.recorder = &MockCountryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCountryRepository) EXPECT() *MockCountryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCountryRepository) Create(ctx context.Context, c *reference.Country) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCountryRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCountryRepository)(nil).Create), ctx, c)
}

// Delete mocks base method.
func (m *MockCountryRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCountryRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCountryRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockCountryRepository) GetByID(ctx context.Context, id string) (*reference.Country, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*reference.Country)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCountryRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCountryRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockCountryRepository) List(ctx context.Context) ([]*reference.Country, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*reference.Country)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCountryRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCountryRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockCountryRepository) Update(ctx context.Context, c *reference.Country) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCountryRepositoryMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCountryRepository)(nil).Update), ctx, c)
}

// MockStateRepository is a mock of StateRepository interface.
type MockStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStateRepositoryMockRecorder
	isgomock struct{}
}

// MockStateRepositoryMockRecorder is the mock recorder for MockStateRepository.
type MockStateRepositoryMockRecorder struct {
	mock *MockStateRepository
}

// NewMockStateRepository creates a new mock instance.
func NewMockStateRepository(ctrl *gomock.Controller) *MockStateRepository {
	mock := &MockStateRepository{ctrl: ctrl}
	mock.recorder = &MockStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateRepository) EXPECT() *MockStateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStateRepository) Create(ctx context.Context, s *reference.State) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStateRepositoryMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStateRepository)(nil).Create), ctx, s)
}

// Delete mocks base method.
func (m *MockStateRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStateRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStateRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockStateRepository) GetByID(ctx context.Context, id string) (*reference.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*reference.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStateRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockStateRepository) List(ctx context.Context, countryID string) ([]*reference.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, countryID)
	ret0, _ := ret[0].([]*reference.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStateRepositoryMockRecorder) List(ctx, countryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStateRepository)(nil).List), ctx, countryID)
}

// ListAll mocks base method.
func (m *MockStateRepository) ListAll(ctx context.Context) ([]*reference.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]*reference.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockStateRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockStateRepository)(nil).ListAll), ctx)
}

// Update mocks base method.
func (m *MockStateRepository) Update(ctx context.Context, s *reference.State) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStateRepositoryMockRecorder) Update(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStateRepository)(nil).Update), ctx, s)
}

// MockPlaceRepository is a mock of PlaceRepository interface.
type MockPlaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlaceRepositoryMockRecorder
	isgomock struct{}
}

// MockPlaceRepositoryMockRecorder is the mock recorder for MockPlaceRepository.
type MockPlaceRepositoryMockRecorder struct {
	mock *MockPlaceRepository
}

// NewMockPlaceRepository creates a new mock instance.
func NewMockPlaceRepository(ctrl *gomock.Controller) *MockPlaceRepository {
	mock := &MockPlaceRepository{ctrl: ctrl}
	mock.recorder = &MockPlaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaceRepository) EXPECT() *MockPlaceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPlaceRepository) Create(ctx context.Context, p *reference.Place) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPlaceRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPlaceRepository)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockPlaceRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPlaceRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPlaceRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockPlaceRepository) GetByID(ctx context.Context, id string) (*reference.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*reference.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPlaceRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPlaceRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPlaceRepository) List(ctx context.Context, stateID string) ([]*reference.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, stateID)
	ret0, _ := ret[0].([]*reference.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPlaceRepositoryMockRecorder) List(ctx, stateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPlaceRepository)(nil).List), ctx, stateID)
}

// ListAll mocks base method.
func (m *MockPlaceRepository) ListAll(ctx context.Context) ([]*reference.Place, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]*reference.Place)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockPlaceRepositoryMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockPlaceRepository)(nil).ListAll), ctx)
}

// Update mocks base method.
func (m *MockPlaceRepository) Update(ctx context.Context, p *reference.Place) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPlaceRepositoryMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPlaceRepository)(nil).Update), ctx, p)
}

// MockOfficeRepository is a mock of OfficeRepository interface.
type MockOfficeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOfficeRepositoryMockRecorder
	isgomock struct{}
}

// MockOfficeRepositoryMockRecorder is the mock recorder for MockOfficeRepository.
type MockOfficeRepositoryMockRecorder struct {
	mock *MockOfficeRepository
}

// NewMockOfficeRepository creates a new mock instance.
func NewMockOfficeRepository(ctrl *gomock.Controller) *MockOfficeRepository {
	mock := &MockOfficeRepository{ctrl: ctrl}
	mock.recorder = &MockOfficeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfficeRepository) EXPECT() *MockOfficeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOfficeRepository) Create(ctx context.Context, o *reference.Office) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOfficeRepositoryMockRecorder) Create(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOfficeRepository)(nil).Create), ctx, o)
}

// Delete mocks base method.
func (m *MockOfficeRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOfficeRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOfficeRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockOfficeRepository) GetByID(ctx context.Context, id string) (*reference.Office, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*reference.Office)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOfficeRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOfficeRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockOfficeRepository) List(ctx context.Context) ([]*reference.Office, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*reference.Office)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOfficeRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOfficeRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockOfficeRepository) Update(ctx context.Context, o *reference.Office) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOfficeRepositoryMockRecorder) Update(ctx, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOfficeRepository)(nil).Update), ctx, o)
}

// MockCategoryRepository is a mock of CategoryRepository interface.
type MockCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockCategoryRepositoryMockRecorder is the mock recorder for MockCategoryRepository.
type MockCategoryRepositoryMockRecorder struct {
	mock *MockCategoryRepository
}

// NewMockCategoryRepository creates a new mock instance.
func NewMockCategoryRepository(ctrl *gomock.Controller) *MockCategoryRepository {
	mock := &MockCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepository) EXPECT() *MockCategoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCategoryRepository) Create(ctx context.Context, c *reference.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCategoryRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoryRepository)(nil).Create), ctx, c)
}

// Delete mocks base method.
func (m *MockCategoryRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCategoryRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCategoryRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockCategoryRepository) GetByID(ctx context.Context, id string) (*reference.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*reference.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCategoryRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCategoryRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockCategoryRepository) List(ctx context.Context) ([]*reference.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*reference.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCategoryRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCategoryRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockCategoryRepository) Update(ctx context.Context, c *reference.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCategoryRepositoryMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCategoryRepository)(nil).Update), ctx, c)
}

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTagRepository) Create(ctx context.Context, t *tag.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTagRepositoryMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagRepository)(nil).Create), ctx, t)
}

// Delete mocks base method.
func (m *MockTagRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTagRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTagRepository) GetByID(ctx context.Context, id string) (*tag.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*tag.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTagRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTagRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTagRepository) List(ctx context.Context, projectID string) ([]*tag.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, projectID)
	ret0, _ := ret[0].([]*tag.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTagRepositoryMockRecorder) List(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTagRepository)(nil).List), ctx, projectID)
}

// MockPersonRepository is a mock of PersonRepository interface.
type MockPersonRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPersonRepositoryMockRecorder
	isgomock struct{}
}

// MockPersonRepositoryMockRecorder is the mock recorder for MockPersonRepository.
type MockPersonRepositoryMockRecorder struct {
	mock *MockPersonRepository
}

// NewMockPersonRepository creates a new mock instance.
func NewMockPersonRepository(ctrl *gomock.Controller) *MockPersonRepository {
	mock := &MockPersonRepository{ctrl: ctrl}
	mock.recorder = &MockPersonRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonRepository) EXPECT() *MockPersonRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPersonRepository) Create(ctx context.Context, p *person.Person) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPersonRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPersonRepository)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockPersonRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPersonRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPersonRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockPersonRepository) GetByID(ctx context.Context, id string) (*person.Person, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*person.Person)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPersonRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPersonRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPersonRepository) List(ctx context.Context, filter person.PersonListFilter) ([]*person.Person, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*person.Person)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPersonRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPersonRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockPersonRepository) Update(ctx context.Context, p *person.Person) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPersonRepositoryMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPersonRepository)(nil).Update), ctx, p)
}

// MockPersonCategoryRepository is a mock of PersonCategoryRepository interface.
type MockPersonCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPersonCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockPersonCategoryRepositoryMockRecorder is the mock recorder for MockPersonCategoryRepository.
type MockPersonCategoryRepositoryMockRecorder struct {
	mock *MockPersonCategoryRepository
}

// NewMockPersonCategoryRepository creates a new mock instance.
func NewMockPersonCategoryRepository(ctrl *gomock.Controller) *MockPersonCategoryRepository {
	mock := &MockPersonCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockPersonCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonCategoryRepository) EXPECT() *MockPersonCategoryRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockPersonCategoryRepository) List(ctx context.Context, personID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, personID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPersonCategoryRepositoryMockRecorder) List(ctx, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPersonCategoryRepository)(nil).List), ctx, personID)
}

// ReplaceAll mocks base method.
func (m *MockPersonCategoryRepository) ReplaceAll(ctx context.Context, personID string, categoryIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAll", ctx, personID, categoryIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceAll indicates an expected call of ReplaceAll.
func (mr *MockPersonCategoryRepositoryMockRecorder) ReplaceAll(ctx, personID, categoryIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAll", reflect.TypeOf((*MockPersonCategoryRepository)(nil).ReplaceAll), ctx, personID, categoryIDs)
}

// MockPersonTagRepository is a mock of PersonTagRepository interface.
type MockPersonTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPersonTagRepositoryMockRecorder
	isgomock struct{}
}

// MockPersonTagRepositoryMockRecorder is the mock recorder for MockPersonTagRepository.
type MockPersonTagRepositoryMockRecorder struct {
	mock *MockPersonTagRepository
}

// NewMockPersonTagRepository creates a new mock instance.
func NewMockPersonTagRepository(ctrl *gomock.Controller) *MockPersonTagRepository {
	mock := &MockPersonTagRepository{ctrl: ctrl}
	mock.recorder = &MockPersonTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonTagRepository) EXPECT() *MockPersonTagRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockPersonTagRepository) List(ctx context.Context, personID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, personID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPersonTagRepositoryMockRecorder) List(ctx, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPersonTagRepository)(nil).List), ctx, personID)
}

// ReplaceAll mocks base method.
func (m *MockPersonTagRepository) ReplaceAll(ctx context.Context, personID string, tagIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAll", ctx, personID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceAll indicates an expected call of ReplaceAll.
func (mr *MockPersonTagRepositoryMockRecorder) ReplaceAll(ctx, personID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAll", reflect.TypeOf((*MockPersonTagRepository)(nil).ReplaceAll), ctx, personID, tagIDs)
}

// MockSupportRecordRepository is a mock of SupportRecordRepository interface.
type MockSupportRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSupportRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockSupportRecordRepositoryMockRecorder is the mock recorder for MockSupportRecordRepository.
type MockSupportRecordRepositoryMockRecorder struct {
	mock *MockSupportRecordRepository
}

// NewMockSupportRecordRepository creates a new mock instance.
func NewMockSupportRecordRepository(ctrl *gomock.Controller) *MockSupportRecordRepository {
	mock := &MockSupportRecordRepository{ctrl: ctrl}
	mock.recorder = &MockSupportRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupportRecordRepository) EXPECT() *MockSupportRecordRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSupportRecordRepository) Create(ctx context.Context, r *support.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSupportRecordRepositoryMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSupportRecordRepository)(nil).Create), ctx, r)
}

// Delete mocks base method.
func (m *MockSupportRecordRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSupportRecordRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSupportRecordRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockSupportRecordRepository) GetByID(ctx context.Context, id string) (*support.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*support.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSupportRecordRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSupportRecordRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockSupportRecordRepository) List(ctx context.Context, filter support.RecordListFilter) ([]*support.Record, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*support.Record)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSupportRecordRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSupportRecordRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockSupportRecordRepository) Update(ctx context.Context, r *support.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSupportRecordRepositoryMockRecorder) Update(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSupportRecordRepository)(nil).Update), ctx, r)
}

// MockMigrationRecordRepository is a mock of MigrationRecordRepository interface.
type MockMigrationRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMigrationRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockMigrationRecordRepositoryMockRecorder is the mock recorder for MockMigrationRecordRepository.
type MockMigrationRecordRepositoryMockRecorder struct {
	mock *MockMigrationRecordRepository
}

// NewMockMigrationRecordRepository creates a new mock instance.
func NewMockMigrationRecordRepository(ctrl *gomock.Controller) *MockMigrationRecordRepository {
	mock := &MockMigrationRecordRepository{ctrl: ctrl}
	mock.recorder = &MockMigrationRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMigrationRecordRepository) EXPECT() *MockMigrationRecordRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMigrationRecordRepository) Create(ctx context.Context, r *migration.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMigrationRecordRepositoryMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMigrationRecordRepository)(nil).Create), ctx, r)
}

// GetByID mocks base method.
func (m *MockMigrationRecordRepository) GetByID(ctx context.Context, id string) (*migration.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*migration.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMigrationRecordRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMigrationRecordRepository)(nil).GetByID), ctx, id)
}

// ListByPerson mocks base method.
func (m *MockMigrationRecordRepository) ListByPerson(ctx context.Context, personID string) ([]*migration.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPerson", ctx, personID)
	ret0, _ := ret[0].([]*migration.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPerson indicates an expected call of ListByPerson.
func (mr *MockMigrationRecordRepositoryMockRecorder) ListByPerson(ctx, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPerson", reflect.TypeOf((*MockMigrationRecordRepository)(nil).ListByPerson), ctx, personID)
}

// MockHouseholdRepository is a mock of HouseholdRepository interface.
type MockHouseholdRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHouseholdRepositoryMockRecorder
	isgomock struct{}
}

// MockHouseholdRepositoryMockRecorder is the mock recorder for MockHouseholdRepository.
type MockHouseholdRepositoryMockRecorder struct {
	mock *MockHouseholdRepository
}

// NewMockHouseholdRepository creates a new mock instance.
func NewMockHouseholdRepository(ctrl *gomock.Controller) *MockHouseholdRepository {
	mock := &MockHouseholdRepository{ctrl: ctrl}
	mock.recorder = &MockHouseholdRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHouseholdRepository) EXPECT() *MockHouseholdRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHouseholdRepository) Create(ctx context.Context, h *household.Household) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, h)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHouseholdRepositoryMockRecorder) Create(ctx, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHouseholdRepository)(nil).Create), ctx, h)
}

// Delete mocks base method.
func (m *MockHouseholdRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHouseholdRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHouseholdRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockHouseholdRepository) GetByID(ctx context.Context, id string) (*household.Household, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*household.Household)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockHouseholdRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockHouseholdRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockHouseholdRepository) List(ctx context.Context, projectID string, page, perPage int) ([]*household.Household, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, projectID, page, perPage)
	ret0, _ := ret[0].([]*household.Household)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockHouseholdRepositoryMockRecorder) List(ctx, projectID, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHouseholdRepository)(nil).List), ctx, projectID, page, perPage)
}

// Update mocks base method.
func (m *MockHouseholdRepository) Update(ctx context.Context, h *household.Household) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, h)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHouseholdRepositoryMockRecorder) Update(ctx, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHouseholdRepository)(nil).Update), ctx, h)
}

// MockHouseholdMemberRepository is a mock of HouseholdMemberRepository interface.
type MockHouseholdMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHouseholdMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockHouseholdMemberRepositoryMockRecorder is the mock recorder for MockHouseholdMemberRepository.
type MockHouseholdMemberRepositoryMockRecorder struct {
	mock *MockHouseholdMemberRepository
}

// NewMockHouseholdMemberRepository creates a new mock instance.
func NewMockHouseholdMemberRepository(ctrl *gomock.Controller) *MockHouseholdMemberRepository {
	mock := &MockHouseholdMemberRepository{ctrl: ctrl}
	mock.recorder = &MockHouseholdMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHouseholdMemberRepository) EXPECT() *MockHouseholdMemberRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m_2 *MockHouseholdMemberRepository) Add(ctx context.Context, m *household.Member) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Add", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockHouseholdMemberRepositoryMockRecorder) Add(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockHouseholdMemberRepository)(nil).Add), ctx, m)
}

// List mocks base method.
func (m *MockHouseholdMemberRepository) List(ctx context.Context, householdID string) ([]*household.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, householdID)
	ret0, _ := ret[0].([]*household.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHouseholdMemberRepositoryMockRecorder) List(ctx, householdID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHouseholdMemberRepository)(nil).List), ctx, householdID)
}

// Remove mocks base method.
func (m *MockHouseholdMemberRepository) Remove(ctx context.Context, householdID, personID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, householdID, personID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockHouseholdMemberRepositoryMockRecorder) Remove(ctx, householdID, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockHouseholdMemberRepository)(nil).Remove), ctx, householdID, personID)
}

// MockPersonNoteRepository is a mock of PersonNoteRepository interface.
type MockPersonNoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPersonNoteRepositoryMockRecorder
	isgomock struct{}
}

// MockPersonNoteRepositoryMockRecorder is the mock recorder for MockPersonNoteRepository.
type MockPersonNoteRepositoryMockRecorder struct {
	mock *MockPersonNoteRepository
}

// NewMockPersonNoteRepository creates a new mock instance.
func NewMockPersonNoteRepository(ctrl *gomock.Controller) *MockPersonNoteRepository {
	mock := &MockPersonNoteRepository{ctrl: ctrl}
	mock.recorder = &MockPersonNoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonNoteRepository) EXPECT() *MockPersonNoteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPersonNoteRepository) Create(ctx context.Context, n *note.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPersonNoteRepositoryMockRecorder) Create(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPersonNoteRepository)(nil).Create), ctx, n)
}

// Delete mocks base method.
func (m *MockPersonNoteRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPersonNoteRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPersonNoteRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockPersonNoteRepository) GetByID(ctx context.Context, id string) (*note.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*note.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPersonNoteRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPersonNoteRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPersonNoteRepository) List(ctx context.Context, personID string) ([]*note.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, personID)
	ret0, _ := ret[0].([]*note.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPersonNoteRepositoryMockRecorder) List(ctx, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPersonNoteRepository)(nil).List), ctx, personID)
}

// MockDocumentRepository is a mock of DocumentRepository interface.
type MockDocumentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentRepositoryMockRecorder
	isgomock struct{}
}

// MockDocumentRepositoryMockRecorder is the mock recorder for MockDocumentRepository.
type MockDocumentRepositoryMockRecorder struct {
	mock *MockDocumentRepository
}

// NewMockDocumentRepository creates a new mock instance.
func NewMockDocumentRepository(ctrl *gomock.Controller) *MockDocumentRepository {
	mock := &MockDocumentRepository{ctrl: ctrl}
	mock.recorder = &MockDocumentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentRepository) EXPECT() *MockDocumentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDocumentRepository) Create(ctx context.Context, d *document.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDocumentRepositoryMockRecorder) Create(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDocumentRepository)(nil).Create), ctx, d)
}

// Delete mocks base method.
func (m *MockDocumentRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDocumentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDocumentRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockDocumentRepository) GetByID(ctx context.Context, id string) (*document.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*document.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDocumentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDocumentRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockDocumentRepository) List(ctx context.Context, personID string) ([]*document.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, personID)
	ret0, _ := ret[0].([]*document.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDocumentRepositoryMockRecorder) List(ctx, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDocumentRepository)(nil).List), ctx, personID)
}

// MockPetRepository is a mock of PetRepository interface.
type MockPetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPetRepositoryMockRecorder
	isgomock struct{}
}

// MockPetRepositoryMockRecorder is the mock recorder for MockPetRepository.
type MockPetRepositoryMockRecorder struct {
	mock *MockPetRepository
}

// NewMockPetRepository creates a new mock instance.
func NewMockPetRepository(ctrl *gomock.Controller) *MockPetRepository {
	mock := &MockPetRepository{ctrl: ctrl}
	mock.recorder = &MockPetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPetRepository) EXPECT() *MockPetRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPetRepository) Create(ctx context.Context, p *pet.Pet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPetRepositoryMockRecorder) Create(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPetRepository)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockPetRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPetRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPetRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockPetRepository) GetByID(ctx context.Context, id string) (*pet.Pet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*pet.Pet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPetRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPetRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPetRepository) List(ctx context.Context, projectID string, page, perPage int) ([]*pet.Pet, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, projectID, page, perPage)
	ret0, _ := ret[0].([]*pet.Pet)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPetRepositoryMockRecorder) List(ctx, projectID, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPetRepository)(nil).List), ctx, projectID, page, perPage)
}

// Update mocks base method.
func (m *MockPetRepository) Update(ctx context.Context, p *pet.Pet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPetRepositoryMockRecorder) Update(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPetRepository)(nil).Update), ctx, p)
}

// MockReportRepository is a mock of ReportRepository interface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
	isgomock struct{}
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// CountByAgeGroup mocks base method.
func (m *MockReportRepository) CountByAgeGroup(ctx context.Context, f report.ReportFilter) ([]report.CountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByAgeGroup", ctx, f)
	ret0, _ := ret[0].([]report.CountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByAgeGroup indicates an expected call of CountByAgeGroup.
func (mr *MockReportRepositoryMockRecorder) CountByAgeGroup(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByAgeGroup", reflect.TypeOf((*MockReportRepository)(nil).CountByAgeGroup), ctx, f)
}

// CountByCategory mocks base method.
func (m *MockReportRepository) CountByCategory(ctx context.Context, f report.ReportFilter) ([]report.CountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCategory", ctx, f)
	ret0, _ := ret[0].([]report.CountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCategory indicates an expected call of CountByCategory.
func (mr *MockReportRepositoryMockRecorder) CountByCategory(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCategory", reflect.TypeOf((*MockReportRepository)(nil).CountByCategory), ctx, f)
}

// CountByCurrentRegion mocks base method.
func (m *MockReportRepository) CountByCurrentRegion(ctx context.Context, f report.ReportFilter) ([]report.CountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCurrentRegion", ctx, f)
	ret0, _ := ret[0].([]report.CountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCurrentRegion indicates an expected call of CountByCurrentRegion.
func (mr *MockReportRepositoryMockRecorder) CountByCurrentRegion(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCurrentRegion", reflect.TypeOf((*MockReportRepository)(nil).CountByCurrentRegion), ctx, f)
}

// CountByIDPStatus mocks base method.
func (m *MockReportRepository) CountByIDPStatus(ctx context.Context, f report.ReportFilter) ([]report.CountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByIDPStatus", ctx, f)
	ret0, _ := ret[0].([]report.CountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByIDPStatus indicates an expected call of CountByIDPStatus.
func (mr *MockReportRepositoryMockRecorder) CountByIDPStatus(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByIDPStatus", reflect.TypeOf((*MockReportRepository)(nil).CountByIDPStatus), ctx, f)
}

// CountByOffice mocks base method.
func (m *MockReportRepository) CountByOffice(ctx context.Context, f report.ReportFilter) ([]report.CountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByOffice", ctx, f)
	ret0, _ := ret[0].([]report.CountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByOffice indicates an expected call of CountByOffice.
func (mr *MockReportRepositoryMockRecorder) CountByOffice(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByOffice", reflect.TypeOf((*MockReportRepository)(nil).CountByOffice), ctx, f)
}

// CountBySex mocks base method.
func (m *MockReportRepository) CountBySex(ctx context.Context, f report.ReportFilter) ([]report.CountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBySex", ctx, f)
	ret0, _ := ret[0].([]report.CountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBySex indicates an expected call of CountBySex.
func (mr *MockReportRepositoryMockRecorder) CountBySex(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBySex", reflect.TypeOf((*MockReportRepository)(nil).CountBySex), ctx, f)
}

// CountBySphere mocks base method.
func (m *MockReportRepository) CountBySphere(ctx context.Context, f report.ReportFilter) ([]report.CountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBySphere", ctx, f)
	ret0, _ := ret[0].([]report.CountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBySphere indicates an expected call of CountBySphere.
func (mr *MockReportRepositoryMockRecorder) CountBySphere(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBySphere", reflect.TypeOf((*MockReportRepository)(nil).CountBySphere), ctx, f)
}

// CountByTag mocks base method.
func (m *MockReportRepository) CountByTag(ctx context.Context, f report.ReportFilter) ([]report.CountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTag", ctx, f)
	ret0, _ := ret[0].([]report.CountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTag indicates an expected call of CountByTag.
func (mr *MockReportRepositoryMockRecorder) CountByTag(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTag", reflect.TypeOf((*MockReportRepository)(nil).CountByTag), ctx, f)
}

// CountConsultations mocks base method.
func (m *MockReportRepository) CountConsultations(ctx context.Context, f report.ReportFilter) ([]report.CountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConsultations", ctx, f)
	ret0, _ := ret[0].([]report.CountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConsultations indicates an expected call of CountConsultations.
func (mr *MockReportRepositoryMockRecorder) CountConsultations(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConsultations", reflect.TypeOf((*MockReportRepository)(nil).CountConsultations), ctx, f)
}

// CountFamilyUnits mocks base method.
func (m *MockReportRepository) CountFamilyUnits(ctx context.Context, f report.ReportFilter) ([]report.CountResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFamilyUnits", ctx, f)
	ret0, _ := ret[0].([]report.CountResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFamilyUnits indicates an expected call of CountFamilyUnits.
func (mr *MockReportRepositoryMockRecorder) CountFamilyUnits(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFamilyUnits", reflect.TypeOf((*MockReportRepository)(nil).CountFamilyUnits), ctx, f)
}

// StatusFlowReport mocks base method.
func (m *MockReportRepository) StatusFlowReport(ctx context.Context, f report.ReportFilter) ([]report.StatusFlow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusFlowReport", ctx, f)
	ret0, _ := ret[0].([]report.StatusFlow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatusFlowReport indicates an expected call of StatusFlowReport.
func (mr *MockReportRepositoryMockRecorder) StatusFlowReport(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusFlowReport", reflect.TypeOf((*MockReportRepository)(nil).StatusFlowReport), ctx, f)
}
