// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lbrty/observer/internal/health (interfaces: Handler)
//
// Generated by this command:
//
//	mockgen -destination=mock/handler.go -package=mock github.com/lbrty/observer/internal/health Handler
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockHandler) Health(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Health", c)
}

// Health indicates an expected call of Health.
func (mr *MockHandlerMockRecorder) Health(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockHandler)(nil).Health), c)
}
