{
  "openapi": "3.0.2",
  "info": {
    "title": "Observer API",
    "description": "Observer API server",
    "version": "0.1.0"
  },
  "paths": {
    "/auth/token": {
      "post": {
        "summary": "Token Login",
        "description": "Login using email and password",
        "operationId": "token_login_auth_token_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginPayload"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TokenResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/auth/token/refresh": {
      "post": {
        "summary": "Token Refresh",
        "description": "Refresh access token using refresh token",
        "operationId": "token_refresh_auth_token_refresh_post",
        "parameters": [
          {
            "description": "Refresh token cookie",
            "required": false,
            "schema": {
              "title": "Refresh Token",
              "type": "string",
              "description": "Refresh token cookie"
            },
            "name": "refresh_token",
            "in": "cookie"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TokenResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "summary": "Token Register",
        "description": "Register using email and password",
        "operationId": "token_register_auth_register_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationPayload"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TokenResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/auth/change-password": {
      "post": {
        "summary": "Change Password",
        "description": "Reset password for user using email",
        "operationId": "change_password_auth_change_password_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ChangePasswordRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/auth/reset-password": {
      "post": {
        "summary": "Reset Password Request",
        "description": "Reset password for user using email",
        "operationId": "reset_password_request_auth_reset_password_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResetPasswordRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/auth/reset-password/{code}": {
      "post": {
        "summary": "Reset Password With Code",
        "description": "Reset password using reset code",
        "operationId": "reset_password_with_code_auth_reset_password__code__post",
        "parameters": [
          {
            "required": true,
            "schema": {
              "title": "Code",
              "type": "string"
            },
            "name": "code",
            "in": "path"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NewPasswordRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "summary": "Health",
        "description": "Simple health endpoint",
        "operationId": "health_health_get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HealthResponse"
                }
              }
            }
          }
        }
      }
    },
    "/mfa/configure": {
      "post": {
        "summary": "Configure Mfa",
        "description": "Setup MFA authentication",
        "operationId": "configure_mfa_mfa_configure_post",
        "parameters": [
          {
            "required": false,
            "schema": {
              "title": "Access Token",
              "type": "string"
            },
            "name": "access_token",
            "in": "cookie"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MFAActivationResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/mfa/setup": {
      "post": {
        "summary": "Setup Mfa",
        "description": "Save MFA configuration and create backup codes.\n\nNOTE:\n    Only the latest private key is used to encrypt secret and backup codes.",
        "operationId": "setup_mfa_mfa_setup_post",
        "parameters": [
          {
            "required": false,
            "schema": {
              "title": "Access Token",
              "type": "string"
            },
            "name": "access_token",
            "in": "cookie"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MFAActivationRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MFABackupCodesResponse"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/mfa/reset": {
      "post": {
        "summary": "Reset Mfa",
        "description": "Reset MFA using one of backup codes\n\nNOTE:\n    HTTP 204 returned anyway to prevent user email brute forcing  because we only\n    want exact matches to check and reset if given backup code is valid.",
        "operationId": "reset_mfa_mfa_reset_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MFAAResetRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ChangePasswordRequest": {
        "title": "ChangePasswordRequest",
        "required": [
          "old_password",
          "new_password"
        ],
        "type": "object",
        "properties": {
          "old_password": {
            "title": "Old Password",
            "type": "string",
            "description": "Old password which user has provided",
            "format": "password",
            "writeOnly": true
          },
          "new_password": {
            "title": "New Password",
            "type": "string",
            "description": "New password which user has provided",
            "format": "password",
            "writeOnly": true
          },
          "totp_code": {
            "title": "Totp Code",
            "type": "string",
            "description": "TOTP code if MFA is active for a given user"
          }
        }
      },
      "HTTPValidationError": {
        "title": "HTTPValidationError",
        "type": "object",
        "properties": {
          "detail": {
            "title": "Detail",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            }
          }
        }
      },
      "HealthResponse": {
        "title": "HealthResponse",
        "required": [
          "status"
        ],
        "type": "object",
        "properties": {
          "status": {
            "title": "Status",
            "type": "string"
          }
        }
      },
      "LoginPayload": {
        "title": "LoginPayload",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "title": "Email",
            "type": "string",
            "description": "E-mail address to login",
            "format": "email"
          },
          "password": {
            "title": "Password",
            "type": "string",
            "description": "Password to login",
            "format": "password",
            "writeOnly": true
          },
          "totp_code": {
            "title": "Totp Code",
            "type": "string",
            "description": "TOTP code if MFA is active for a given user"
          }
        }
      },
      "MFAAResetRequest": {
        "title": "MFAAResetRequest",
        "required": [
          "email",
          "backup_code"
        ],
        "type": "object",
        "properties": {
          "email": {
            "title": "Email",
            "type": "string",
            "description": "User email",
            "format": "email"
          },
          "backup_code": {
            "title": "Backup Code",
            "type": "string",
            "description": "MFA backup code"
          }
        }
      },
      "MFAActivationRequest": {
        "title": "MFAActivationRequest",
        "required": [
          "secret",
          "totp_code"
        ],
        "type": "object",
        "properties": {
          "secret": {
            "title": "Secret",
            "type": "string",
            "description": "TOTP secret",
            "format": "password",
            "writeOnly": true
          },
          "totp_code": {
            "title": "Totp Code",
            "type": "string",
            "description": "TOTP code to validate and save for user",
            "format": "password",
            "writeOnly": true
          }
        }
      },
      "MFAActivationResponse": {
        "title": "MFAActivationResponse",
        "required": [
          "secret",
          "qr_image"
        ],
        "type": "object",
        "properties": {
          "secret": {
            "title": "Secret",
            "type": "string",
            "description": "TOTP secret"
          },
          "qr_image": {
            "title": "Qr Image",
            "type": "string",
            "description": "Base64 QR code image"
          }
        }
      },
      "MFABackupCodesResponse": {
        "title": "MFABackupCodesResponse",
        "required": [
          "backup_codes"
        ],
        "type": "object",
        "properties": {
          "backup_codes": {
            "title": "Backup Codes",
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "List of backup codes"
          }
        }
      },
      "NewPasswordRequest": {
        "title": "NewPasswordRequest",
        "required": [
          "password"
        ],
        "type": "object",
        "properties": {
          "password": {
            "title": "Password",
            "type": "string",
            "description": "Password which user has provided",
            "format": "password",
            "writeOnly": true
          }
        }
      },
      "RegistrationPayload": {
        "title": "RegistrationPayload",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "title": "Email",
            "type": "string",
            "description": "E-mail address of a user",
            "format": "email"
          },
          "password": {
            "title": "Password",
            "type": "string",
            "description": "Password which user has provided",
            "format": "password",
            "writeOnly": true
          }
        }
      },
      "ResetPasswordRequest": {
        "title": "ResetPasswordRequest",
        "required": [
          "email"
        ],
        "type": "object",
        "properties": {
          "email": {
            "title": "Email",
            "type": "string",
            "description": "E-mail address of a user",
            "format": "email"
          }
        }
      },
      "TokenResponse": {
        "title": "TokenResponse",
        "required": [
          "access_token",
          "refresh_token"
        ],
        "type": "object",
        "properties": {
          "access_token": {
            "title": "Access Token",
            "type": "string",
            "description": "JWT access token"
          },
          "refresh_token": {
            "title": "Refresh Token",
            "type": "string",
            "description": "JWT refresh token"
          }
        }
      },
      "ValidationError": {
        "title": "ValidationError",
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "type": "object",
        "properties": {
          "loc": {
            "title": "Location",
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            }
          },
          "msg": {
            "title": "Message",
            "type": "string"
          },
          "type": {
            "title": "Error Type",
            "type": "string"
          }
        }
      }
    }
  }
}