import { mock } from "bun:test";

const stub = (name: string) => (props: Record<string, unknown>) => (
  <span data-testid={name} {...props} />
);

mock.module("@phosphor-icons/react", () => ({
  ArrowLeftIcon: stub("ArrowLeftIcon"),
  ArrowSquareOutIcon: stub("ArrowSquareOutIcon"),
  ArrowsClockwiseIcon: stub("ArrowsClockwiseIcon"),
  CalendarBlankIcon: stub("CalendarBlankIcon"),
  BuildingsIcon: stub("BuildingsIcon"),
  CaretDownIcon: stub("CaretDownIcon"),
  CaretLeftIcon: stub("caret-left"),
  CaretRightIcon: stub("caret-right"),
  CaretUpDownIcon: stub("CaretUpDownIcon"),
  CaretUpIcon: stub("CaretUpIcon"),
  ChartBarIcon: stub("ChartBarIcon"),
  CheckIcon: stub("check-icon"),
  CopySimpleIcon: stub("CopySimpleIcon"),
  DownloadSimpleIcon: stub("DownloadSimpleIcon"),
  EyeIcon: stub("EyeIcon"),
  FileArchiveIcon: stub("FileArchiveIcon"),
  FileAudioIcon: stub("FileAudioIcon"),
  FileCsvIcon: stub("FileCsvIcon"),
  FileDocIcon: stub("FileDocIcon"),
  FileIcon: stub("FileIcon"),
  FileImageIcon: stub("FileImageIcon"),
  FilePdfIcon: stub("FilePdfIcon"),
  FilePngIcon: stub("FilePngIcon"),
  FilePptIcon: stub("FilePptIcon"),
  FileSvgIcon: stub("FileSvgIcon"),
  FileTextIcon: stub("FileTextIcon"),
  FileVideoIcon: stub("FileVideoIcon"),
  FileXlsIcon: stub("FileXlsIcon"),
  FilesIcon: stub("FilesIcon"),
  FolderSimpleIcon: stub("FolderSimpleIcon"),
  FunnelIcon: stub("FunnelIcon"),
  GlobeIcon: stub("GlobeIcon"),
  HandHeartIcon: stub("HandHeartIcon"),
  HouseSimpleIcon: stub("HouseSimpleIcon"),
  MagnifyingGlassIcon: stub("MagnifyingGlassIcon"),
  PathIcon: stub("PathIcon"),
  PawPrintIcon: stub("PawPrintIcon"),
  PencilSimpleIcon: stub("PencilSimpleIcon"),
  PlusIcon: stub("PlusIcon"),
  PrinterIcon: stub("PrinterIcon"),
  SignOutIcon: stub("SignOutIcon"),
  TagIcon: stub("TagIcon"),
  TrashIcon: stub("TrashIcon"),
  UploadSimpleIcon: stub("UploadSimpleIcon"),
  UserCircleIcon: stub("UserCircleIcon"),
  UsersIcon: stub("UsersIcon"),
  WarningIcon: stub("warning-icon"),
  UserFocusIcon: stub("UserFocusIcon"),
  XIcon: stub("XIcon"),
}));
